# -*- coding: utf-8 -*-
"""Ejercicio 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lWal_-XM6gvShM7fKAg_aXJtu2aeZEt3

# Nombre: Paola López Neira

### Ejercicio 4.4

Suponga que los campos ``info`` de los nodos externos de un árbol contienen solo números y escriba una función que pueda invocarse como ``formula.evaluar()``, que al ser ejecutada entregue el valor numérico  de la fórmula representada por el árbol. Modifique a continuación la definición de las clases ``Arbol``, ``Nodoi`` y ``Nodoe`` para que incluyan la nueva función ``evaluar()``. Note que tiene que implementar la función ``evaluar()`` en las tres clases.
"""

class Nodoi: #nodos internos corresponden a los operadores
    def __init__(self, izq, info, der):
        self.izq=izq
        self.info=info
        self.der=der

    def evaluar(self):
      letra=self.info
      operador_1=self.izq.evaluar()
      operador_2=self.der.evaluar()
      if letra=="+":
        return (operador_1 + operador_2)
      if letra=="/":
        return (operador_1/operador_2)
      if letra=="-":
        return (operador_1 - operador_2)
      if letra=="*":
        return (operador_1*operador_2)

class Nodoe: #nodos externos corresponden a los que queremos calcular
    def __init__(self, info=""):
        self.info=info
    def evaluar(self):
        return self.info

class Arbol:
    def __init__(self,raiz=Nodoe()):
        self.raiz=raiz
    def evaluar(self):
        return self.raiz.evaluar()

"""Pruébela a continuación:"""

formula= Arbol(
            Nodoi(
                Nodoi(Nodoe(5),"+",Nodoe(2)),
                "*",
                Nodoi(
                    Nodoe(8),
                    "-",
                    Nodoi(Nodoe(9),"/",Nodoe(3))
                )
            )
        )
print(formula.evaluar())