# -*- coding: utf-8 -*-
"""Ejercicio10PLN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LglYrbjzEh-9W0XHx-a15bZn3hbaqFay

### Ejercicio 7.3 (Merge de listas con repeticiones)
#Paola López Neira
Suponga que se desea mezclar dos listas ordenadas de manera ascendente en las cuales puede haber elementos repetidos. Estas listas se representan en forma compacta como una secuencia de tuplas en que para cada elemento se indica su *multiplicidad*, es decir, el número de veces que se repite. Por ejemplo, la lista
```
[(12,2),(34,1),(56,3),(74,1),(81,1)]
```
es la representación compacta de la lista
```
[12,12,34,56,56,56,74,81]
```
Se pide escribir un método ``merge(a,b)`` que reciba como argumento dos listas compactas ``a`` y ``b`` y retorne el resultado de mezclarlas. El resultado debe estar también en formato compacto.

Para esto, usted debe modificar el método ``merge``del apunte, el que aparece a continuación:
"""

def merge(a,b):
    i=0
    j=0
    while i<len(a) or j<len(b):
        if j>=len(b) or (i<len(a) and a[i][0]<=b[j][0]):
            if a[i][0]==b[j][0]:
              c = (a[i][0], a[i][1] + b[j][1])
              yield c
              i=i+1
              j=j+1
            else:
              yield a[i]
              i=i+1
        else:
            yield b[j]
            j=j+1

"""y luego debe probarlo ejecutando el código siguiente:"""

a=[(12,2),(34,1),(56,3),(74,1),(81,1)]
b=[(10,3),(12,5),(65,1),(74,1),(90,3)]
c=[x for x in merge(a,b)]
print(c)