# -*- coding: utf-8 -*-
"""Ejercicio2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gZhbpzJ1MMg7NPMrk8P6i3RrDrLOSIDS

**Nombre:** Paola López Neira
"""

def genera_binarios(a,k,n):
    #Aquí debes definir tu código
    n=len(a) #n representa el largo que queremos de la matriz
    if k==n:
      print(a) #imprime los números binarios generados
    else: #acá creamos la función recursiva
      a[k]=0 #primero añadimos los ceros
      genera_binarios(a,k+1,n)
      a[k]=1 #finalmente se añaden los unos
      genera_binarios(a,k+1,n)

import numpy as np
n = 4
a = np.empty(n,dtype=int) # arreglo de largo n sin inicializar
#genera_binarios(a,0,len(a))

genera_binarios(a,0,4)