# -*- coding: utf-8 -*-
"""Tarea 2 PLN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DMckZ904Xg6ioTbMjUM7uNIlXaZHcxoY

# CC3001 Otoño 2022 Tarea 2 [Paola López Neira]

## Expandir listas

### Profesores
Sección 1 Iván Sipirán •
Sección 2 Patricio Poblete •
Sección 3 Nelson Baloian

# Enunciado

En esta tarea se deberá implementar una función ``expandir(L)`` que construya y retorne una lista expandida a partir de otra lista dada ``L``, de la manera que se indica a continuación.

La entrada para la función es una lista python que contiene elementos que pueden ser de tipo lista, tupla o un valor simple de cualquier tipo. El resultado debe ser una lista solo con elementos simples, que resulta de aplicar las siguientes reglas a cada elemento de la lista original:
  - si el elemento es un valor simple, éste se agrega a la lista resultante
   - Ejemplo: si la lista de entrada es $[2, 3]$ la lista de salida es $[2,3]$
  - si el elemento es a su vez también una lista, entonces cada uno de los    elementos de esa lista lista se agrega a la lista resultante como un elemento más.
   - Ejemplo: si la lista de entrada es $[2, 3, [1, 2]]$ la lista de salida es $[2,3,1,2] $
  - si el elemento es una tupla, entonces el primer elemento será un entero, digamos $x$ y el segundo una lista que llamaremos $s$. En este caso, hay que agregar $x$ veces los elementos de la lista $s$.
    - Ejemplo: si la lista de entrada contiene $[1, (2,[2,3])]$ la lista de salida es $[1, 2, 3, 2, 3] $

Lo que hace interesante este problema, es que cada elemento de una lista puede ser a su vez necesitar una expansión como explicamos anteriormente (elementos simples, listas o tuplas), por lo cual se deberá aplicar recursión en forma inteligente para resolver el problema.
    
   - Ejemplo: una lista de entrada puede ser $[5,[2,[2,[2,4,[0,(3,[1,2])]]]]]$ y la salida debe ser $[5, 2, 2, 2, 4, 0, 1, 2, 1, 2, 1, 2]$

   Se le pide entonces escribir la función siguiente:
"""

def expandir(L):
  #incluir aqui sus instrucciones
  if L == []: #si es lista vacia, devolvemos la misma lista
    return L
  else: #nos ponemos en casos
    for i in L: #recorremos la lista para analizar si se trata de una lista, de una tupla o de int
      if type(i) is list: #si es lista la añadimos
        x = L.index(i) #Modificamos la misma lista L
        L.remove(i)
        L[x:x] = i #De esta forma añadimos la lista en una misma lista
        return expandir(L)
      if type(i) is tuple: #si es tupla, repetimos la cantidad i[0] veces el resto de la tupla
        x = L.index(i)
        L.remove(i)
        y = 0
        z = i[0] #Es el primer número que aparece en la lista, el cual nos indicará cuantas veces debemos repetir lo otro
        while y < z: #mientras i[0] sea mayor a cero, seguiremos añadiendo los mismos elementos en la lista
           L[x:x]=i[1]
           y = y + 1
        return expandir(L)
      if all(isinstance(i,int) for i in L): #En esta parte revisamos que todos los elementos de la lista sean int, de ser así retornamos la lista L
           return L

"""Para chequear si su función hace lo que requiere use los siguientes chequeos:


"""

if expandir([1,2,3]) == [1,2,3]: print("OK");
else: print("Error")
if expandir([1, (2, [2, 3, [1, 2]]),5]) == [1, 2, 3, 1, 2, 2, 3, 1, 2, 5]: print("OK");
else: print("Error")
if expandir([1, (5,[1,3])]) == [1, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3]: print("OK");
else: print("Error")
if expandir([]) == []: print("OK");
else: print("Error")
if expandir([2,(3,[5,3,[2,(3,[2,4])]])]) == [2, 5, 3, 2, 2, 4, 2, 4, 2, 4, 5, 3, 2, 2, 4, 2, 4, 2, 4, 5, 3, 2, 2, 4, 2, 4, 2, 4]:
  print("OK");
else: print("Error")
if expandir([3, (2, [1, (5,[1,3])])]) == [3, 1, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3]:
  print("OK")
else: print("Error")

"""## ¿Qué hay que entregar?

Usted debe crear una copia de este documento (del menú seleccionar "Archivo" o "File" y de ahi la opción "guardar copia en Drive" o "save a copy in Drive"). Este nuevo documento (notebook de Colab) es el que debe modificar para luego compartirlo con la opción "Cualquier usuario de internet con este enlace puede ver esto" (o “Anyone on the internet with this link can view”). Esta opción se encuentra disponible en la parte superior derecha de su notebook, en el botón "Compartir" (o "Share"). Una vez que tenga disponible el enlace, colocarlo en la descripción de la entrega de su tarea. No olvide colocar su nombre dentro del notebook.
"""
